In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('output/test.csv')

In [4]:
df

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,0.004012,0.004114,0.004025,0.003715,0.003475,0.003302,0.003224,0.003170,0.003132,0.003094,...,0.000530,0.000475,0.000593,0.000949,0.000732,0.001032,0.001792,0.001076,0.001063,0.001051
1,0.011018,0.010920,0.012424,0.008107,0.009397,0.009057,0.007875,0.008481,0.009525,0.009198,...,0.021923,0.042297,0.052122,0.062847,0.066523,0.062780,0.061723,0.064524,0.063183,0.061877
2,0.081446,0.039413,0.024996,0.025154,0.030603,0.025535,0.025631,0.019249,0.010794,0.013673,...,0.237919,0.309850,0.343202,0.276439,0.294178,0.275844,0.276931,0.277326,0.281711,0.286553
3,0.840248,0.870564,0.884801,0.865110,1.008988,1.115317,1.056271,0.862762,1.083163,1.008288,...,0.840973,0.700643,0.688852,0.876584,0.885252,1.033697,1.072202,1.145576,1.142201,1.141177
4,0.044491,0.052940,0.059342,0.065032,0.070982,0.060263,0.055055,0.072337,0.073134,0.072556,...,0.098891,0.092952,0.093270,0.084752,0.091026,0.090168,0.102383,0.100445,0.100595,0.100756
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,0.018532,0.022629,0.028110,0.029685,0.032928,0.036096,0.045395,0.055003,0.066458,0.071474,...,0.275384,0.251010,0.244001,0.257322,0.283202,0.334569,0.352394,0.386642,0.411842,0.403926
131,0.034930,0.028365,0.030257,0.034472,0.029080,0.033561,0.029763,0.034074,0.031440,0.036248,...,0.016697,0.048156,0.051966,0.048671,0.038192,0.038855,0.030984,0.030662,0.030309,0.029971
132,0.076295,0.069458,0.064290,0.065685,0.073726,0.075593,0.089487,0.092597,0.083634,0.075898,...,0.076472,0.077457,0.076833,0.073456,0.083038,0.093065,0.098249,0.103195,0.103016,0.102868
133,0.023006,0.019423,0.017450,0.017143,0.013353,0.013884,0.015649,0.016764,0.014870,0.012337,...,0.031050,0.039156,0.041107,0.040962,0.040128,0.049181,0.052462,0.063036,0.061942,0.060864
134,0.037908,0.037850,0.032322,0.031190,0.023438,0.035862,0.036391,0.039551,0.039142,0.035271,...,0.027454,0.039948,0.030217,0.031278,0.038694,0.047321,0.049179,0.049565,0.049428,0.049258

In [5]:
df_perc_change = df.pct_change(axis='columns') * 100

In [6]:
df_perc_change

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,NaN,2.549610,-2.172645,-7.693016,-6.467459,-4.983606,-2.359112,-1.672680,-1.186944,-1.229099,...,0.143499,-10.374868,24.856923,60.028111,-22.835698,40.878309,73.723002,-39.976831,-1.163889,-1.166280
1,NaN,-0.880827,13.764134,-34.744786,15.916279,-3.623464,-13.053853,7.694829,12.315781,-3.428631,...,-6.218114,92.932391,23.227899,20.575577,5.850148,-5.627576,-1.683616,4.538047,-2.078153,-2.066921
2,NaN,-51.608299,-36.578512,0.631865,21.661048,-16.560343,0.376215,-24.901234,-43.925439,26.676342,...,33.615182,30.233713,10.763673,-19.452968,6.417173,-6.232485,0.394049,0.142727,1.581373,1.718763
3,NaN,3.607964,1.635380,-2.225467,16.631288,10.538089,-5.294062,-18.319974,25.545940,-6.912691,...,-9.006344,-16.686594,-1.682893,27.252754,0.988929,16.768610,3.724986,6.843279,-0.294621,-0.089584
4,NaN,18.991531,12.093261,9.588627,9.149021,-15.101403,-8.642123,31.391456,1.102075,-0.790746,...,6.024908,-6.005396,0.341686,-9.131851,7.402881,-0.942739,13.547045,-1.893336,0.149569,0.159795
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,NaN,22.108317,24.221866,5.602601,10.927078,9.621716,25.761084,21.165266,20.825652,7.547312,...,1.196089,-8.850998,-2.792502,5.459554,10.057251,18.138144,5.327709,9.718721,6.517474,-1.921940
131,NaN,-18.795586,6.672405,13.930332,-15.642886,15.408097,-11.316083,14.485938,-7.730626,15.290568,...,-52.753129,188.406595,7.913154,-6.340682,-21.531136,1.735636,-20.257179,-1.039670,-1.151033,-1.115213
132,NaN,-8.960201,-7.441522,2.171017,12.240434,2.532455,18.379861,3.475694,-9.679415,-9.250243,...,-1.011143,1.287359,-0.804970,-4.395831,13.044958,12.075600,5.569598,5.034206,-0.173443,-0.143302
133,NaN,-15.573742,-10.159270,-1.757400,-22.107634,3.976838,12.711928,7.124400,-11.296803,-17.039038,...,2.983108,26.106969,4.982870,-0.354430,-2.036183,22.560994,6.672515,20.154569,-1.735116,-1.740597
134,NaN,-0.153594,-14.604884,-3.501801,-24.854464,53.008753,1.475800,8.683030,-1.035466,-9.888649,...,19.712463,45.508054,-24.358288,3.509605,23.710575,22.296744,3.926048,0.785730,-0.277892,-0.343331

In [9]:
((-1.166280) + (-1.163889) + (-39.976831) + 73.723002 + 40.878309)/5

14.458862199999999

In [10]:
((-1.163889) + (-39.976831) + 73.723002 + 40.878309 + (-22.835698))/5

10.124978599999999

In [9]:
df_rolling_average = df_perc_change.rolling(window=5, axis='columns').mean()

In [10]:
df_rolling_average

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,NaN,NaN,NaN,NaN,NaN,-3.753423,-4.735167,-4.635174,-3.333960,-2.286288,...,-9.730024,-11.587706,-0.192725,15.390408,10.363593,18.510555,35.330129,22.363378,10.124978,14.458862
1,NaN,NaN,NaN,NaN,NaN,-1.913733,-4.348338,-5.562199,3.849914,-0.019068,...,-3.336211,16.392307,16.857118,22.623236,27.273580,27.391688,8.468486,4.730516,0.199770,-1.383644
2,NaN,NaN,NaN,NaN,NaN,-16.490848,-6.093946,-3.758490,-12.669951,-11.666892,...,31.182747,22.379883,23.666918,15.619513,12.315355,4.345821,-1.622111,-3.746301,0.460567,-0.479114
3,NaN,NaN,NaN,NaN,NaN,6.037451,4.257046,0.265975,5.820256,1.111460,...,3.531213,1.269110,-12.704657,-2.479197,0.173170,5.328161,9.410477,11.115712,5.606237,5.390534
4,NaN,NaN,NaN,NaN,NaN,6.944208,1.417477,5.277116,3.579805,1.591852,...,3.426270,0.420539,0.744100,-0.250540,-0.273554,-1.667084,2.243405,1.796400,3.652684,2.204067
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,NaN,NaN,NaN,NaN,NaN,14.496315,15.226869,14.615549,17.660159,16.984206,...,7.734137,3.168632,2.569031,0.164235,1.013879,4.402290,7.238031,9.740276,9.951860,7.556022
131,NaN,NaN,NaN,NaN,NaN,0.314472,1.810373,3.373080,-0.959112,5.227579,...,-6.092171,28.491205,24.958527,24.545269,23.138960,34.036713,-7.696041,-9.486606,-8.448676,-4.365492
132,NaN,NaN,NaN,NaN,NaN,0.108437,5.576449,7.759892,5.389806,1.091670,...,-5.720679,-5.851452,-5.204085,-2.314439,1.624075,4.241423,5.097871,6.265706,7.110184,4.472532
133,NaN,NaN,NaN,NaN,NaN,-9.124242,-3.467108,-0.010374,-1.918254,-0.904535,...,10.134592,16.714727,21.164013,12.324330,6.336467,10.252044,6.365153,9.399493,9.123356,9.182473
134,NaN,NaN,NaN,NaN,NaN,1.978802,2.304681,6.962264,7.455531,10.448693,...,10.084794,28.335633,23.923559,12.061116,13.616482,14.133338,5.816937,10.845740,10.088241,5.277460

In [15]:
series = df_rolling_average[str('2019')]

In [16]:
series

0      10.124978
1       0.199770
2       0.460567
3       5.606237
4       3.652684
         ...
130     9.951860
131    -8.448676
132     7.110184
133     9.123356
134    10.088241
Name: 2019, Length: 135, dtype: float64